title: Lei's Notes
author: Lei Lei
email: Lei.Lei2@nottingham.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  My private lab notes on materials science including several projects on perovskite structure materials and computational research.
baseurl: "/Materials-Research-Notes" # the subpath of your site, e.g. /blog
url: "https://lei-lei-alpha.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: "Lei-Lei-alpha/Materials-Research-Notes" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

twitter_username: leilei78814998
github_username:  Lei-Lei-alpha

# Build settings
syntax_highlighter_style: colorful
toc:
    enabled: true
    h_min: 1
    h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown, mkdown, mkdn, mkd, md

plugins:
  - jekyll-diagrams

# Permalinks
# permalink:      /:categories/:year-:month-:day-:title:output_ext

# Define new collection
collections:
  - Chap1-Coding
  - Chap2-ML
  - Chap3-MatNotes
  - Chap4-HSTORE
  - Chap5-CompMat
  - Chap6-Visualisation
  - Chap7-sys_ssh
  - ChapX-Info

collections:
  Chap1-Coding:
    output: true
    permalink: /:collection/:path/
  Chap2-ML:
    output: true
    permalink: /:collection/:path/
  Chap3-MatNotes:
    output: true
    permalink: /:collection/:path/
  Chap4-HSTORE:
    output: true
    permalink: /:collection/:path/
  Chap5-CompMat:
    output: true
    permalink: /:collection/:path/
  Chap6-Visualisation:
    output: true
    permalink: /:collection/:path/
  Chap7-sys_ssh:
    output: true
    permalink: /:collection/:path/
  ChapX-Info:
    output: true
    permalink: /:collection/:path/

#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-remote-theme

remote_theme: sighingnow/jekyll-gitbook